### ISSUE TITLE
resize images with css background url

### ISSUE THREAD

**Issue by sergerdn** [juliomrqz/nuxt-optimized-images#230]
Hi, there. Is there any example how I can use resizing images and css together?   
I need something like this:
```css
    .intro-image {
       @include media-breakpoint-up(xl) {
       // doesn't work in my experience
         background: url("~@/assets/images/1_main.jpg?resize&size=300") no-repeat center;
       }
        background-size: cover;
    }
```
